import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/components/Providers";
import { ThemeProvider } from "@/components/ThemeProvider";
import { AppSidebar } from "@/components/AppSidebar";
import SwipeNavigationHandler from "@/components/SwipeNavigationHandler";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            themes={["light", "dark", "paper", "cyber"]}
          >
            <div className="flex flex-col md:flex-row min-h-screen bg-background text-foreground">
              <AppSidebar />
              <main className="flex-1 w-full overflow-y-auto overflow-x-hidden">
                <SwipeNavigationHandler>
                  {children}
                </SwipeNavigationHandler>
              </main>
            </div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
